CREATE DATABASE ALOJAMIENTOS_FULLSTACK;

USE ALOJAMIENTOS_FULLSTACK;

CREATE TABLE USERS(
	USERID INT PRIMARY KEY AUTO_INCREMENT,
	`NAME` VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(10)NOT NULL,
    ADDRESS VARCHAR(200) NOT NULL,
    DATE_BIRTH DATE NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    `ROLE` VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL UNIQUE CHECK(EMAIL REGEXP'/.+\@.+\..+/'),
    `PASSWORD` VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ACCOMODATION(
	ACCOMODATION_ID INT PRIMARY KEY AUTO_INCREMENT,
    ADDRESS VARCHAR(200) NOT NULL,
	COUNTRY VARCHAR(50) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    PRICE FLOAT NOT NULL,
    ROOMS INT NOT NULL,
    BATHROOMS INT NOT NULL,
    SIZE VARCHAR(30) NOT NULL,
    IMAGE TEXT NOT NULL,
    `DESCRIPTION` VARCHAR(255)
);

CREATE TABLE RESERVATIONS (
	RESERVATIONS_ID  INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    ACCOMODATION_ID INT NOT NULL,
    DATE_START_RESERVATION DATE NOT NULL,
    DATE_END_RESERVATION DATE NOT NULL,
	PAYMENTMETHOD VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ACCOMODATION_ID) REFERENCES ACCOMODATION(ACCOMODATION_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USERID)
);
